version: '3.8'

services:
  backend:
    tty: true
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    expose:
      - "5000" # Publishes 5433 to other containers but NOT to host machine
    ports:
      - "5000:5000"
#    command: /wait && air
    environment:
      WAIT_HOSTS: postgres-database:5433
    volumes:
      - .:/src
  postgres-database:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: route_admin
      POSTGRES_USER: route_admin
    expose:
      - "5433" # Publishes 5433 to other containers but NOT to host machine
    ports:
      - "5433:5433"
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: -p 5433
# Volume names
volumes:
  go-source:
  pgdata: